Add shoppingcart
slizko1/Online-Book-Store pull request #14
Opened 2024-05-23 16:57 UTC by slizko1

2024-05-25 11:23 UTC, d1sam requested changes
Good job, but there are some changes, that should be done according to my comments.

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/controller/CategoryController.java
> +                                      @RequestBody @Valid CategoryDto categoryDto) {
these change are not related to this hw.

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY)
```

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/model/CartItem.java
> +    private int quantity;
```suggestion
    private Integer quantity;
```

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/model/CartItem.java
> +    private int quantity;
I prefer to use the wrapped type as you can tell if the object has been saved/loaded to/from the database whether or not the id value is null.

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/controller/ShoppingCartController.java
> +        return shoppingCartService.update(cartItemId, requestDto);
also you should check that cartItemId is related to user, that sends this request.

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/controller/ShoppingCartController.java
> +        shoppingCartService.deleteCartItemById(cartItemId);
also you should check that cartItemId is related to user, that sends this request.

2024-05-25 11:23 UTC, d1sam commented on src/main/resources/db/changelog/changes/11-create-cart-items-table.yaml
let's add unique constraint to book_id, shopping_cart_id

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    private void validateId(Long id) {
```suggestion
    private void checkExistenceByID(Long id) {
```

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    public void deleteCartItemById(Long cartItemId) {
```suggestion
    @Transactional
    public void deleteCartItemById(Long cartItemId) {
```

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Override
```suggestion
    @Override
    @Transactional
```

2024-05-25 11:23 UTC, d1sam commented on src/main/java/com/samoilenko/onlinebookstore/service/impl/ShoppingCartServiceImpl.java
> +    @Transactional
```suggestion
    @Transactional(readOnly = true)
```

2024-05-26 17:57 UTC, slizko1 commented on src/main/resources/db/changelog/changes/11-create-cart-items-table.yaml
Why do we need to have unique constraint in shopping_cart_id? We may have several cartItems related to one shoppingCart

2024-05-27 09:23 UTC, yevheniisynytsia approved these changes
Nice!

2024-05-27 09:23 UTC, yevheniisynytsia commented on src/main/java/com/samoilenko/onlinebookstore/dto/categorydtos/CategoryRequestDto.java
> +        String description
please add size validation so that if more than expected the failure will occur on the controller level instead of db level

2024-05-27 11:13 UTC, merged