BookRepository start extends JpaRepository. Update and delete methods…
slizko1/Online-Book-Store pull request #3
Opened 2024-04-28 19:28 UTC by slizko1

… and Liquibase was added. spring.jpa.hibernate.ddl-auto property value was changed to validate.  soft delete concept for the Book entity was implemented.

2024-04-28 21:24 UTC, AnyaRatusnyak commented
Well done ))

2024-04-29 09:14 UTC, karma-o requested changes
Looks good so far, left several suggestions

2024-04-29 09:14 UTC, karma-o commented on src/main/java/com/samoilenko/onlinebookstore/controller/BookController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Let's also add `created` response status for `createBook()` method

2024-04-29 09:14 UTC, karma-o commented on src/main/java/com/samoilenko/onlinebookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
where is deprecated so let's use `@SqlRestriction` instead, if it doesn't work - try to change the type of `is_deleted` column in liquibase to `BIT`

2024-04-29 09:14 UTC, karma-o commented on src/main/java/com/samoilenko/onlinebookstore/service/impl/BookServiceImpl.java
> +    }
first, we need to check if the book with such an id exists, if not - throw `EntityNotFountException`, and than act, fix for both methods

2024-04-29 09:14 UTC, karma-o commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                  type: varchar(255)
description and URL's of the image are usually pretty ling, let's raise the max length to at least 500

2024-05-02 08:19 UTC, karma-o approved these changes
GJ!

2024-05-02 08:19 UTC, karma-o commented on src/main/java/com/samoilenko/onlinebookstore/service/impl/BookServiceImpl.java
> +        }
code duplication, extract into a private method

2024-05-02 08:57 UTC, merged