GlobalExceptionHandler and data validation was added
slizko1/Online-Book-Store pull request #4
Opened 2024-05-01 20:04 UTC by slizko1

2024-05-01 20:46 UTC, kaiiiseeel requested changes
Everything looks very good, but in my opinion it needs a little work.

2024-05-01 20:46 UTC, kaiiiseeel commented on src/main/java/com/samoilenko/onlinebookstore/dto/BookRequestDto.java
> +    @NotNull
I could be wrong, but as far as I know, for strings it is better to use NotBlank instead of NotNull.

2024-05-01 20:46 UTC, kaiiiseeel commented on src/main/java/com/samoilenko/onlinebookstore/dto/BookRequestDto.java
>      private String isbn;
You should also validate the ISBN (International Standard Book Number) as every book must have one and follow the exact pattern. (P.S we have special annotation for it)

2024-05-02 09:42 UTC, yevheniisynytsia requested changes
Please fix conflicts. Try to remember that if you merge something and there is a dependent branch, then you must update it as well

2024-05-02 09:42 UTC, yevheniisynytsia commented on src/main/java/com/samoilenko/onlinebookstore/service/impl/BookServiceImpl.java
> +    private void idValidation(Long id) {
```suggestion
    private void validateId(Long id) {
```
method name is almost always an action

2024-05-02 09:42 UTC, yevheniisynytsia commented on src/main/java/com/samoilenko/onlinebookstore/exception/CustomGlobalExceptionHandler.java
> +    protected ResponseEntity<Object> handleExceptionInternal(
let's make it simpler:
add a similar method
`private ResponseEntity<Object> getResponseEntity(HttpStatus status, Object errors) {
        Map<String, Object> body = new LinkedHashMap<>();
        body.put("timestamp", LocalDateTime.now());
        body.put("status", status.getReasonPhrase());
        body.put("errors", errors);
        return new ResponseEntity<>(body, status);
    }` 
    and you'll reuse it in all exception handling methods

2024-05-02 09:42 UTC, yevheniisynytsia commented on src/main/java/com/samoilenko/onlinebookstore/dto/BookRequestDto.java
> +    @NotBlank
please add messages

2024-05-02 09:42 UTC, yevheniisynytsia commented on src/main/java/com/samoilenko/onlinebookstore/dto/BookRequestDto.java
> +    @ISBN
null is valid case for ISBN https://docs.jboss.org/hibernate/stable/validator/api/org/hibernate/validator/constraints/ISBN.html

2024-05-02 14:09 UTC, slizko1 commented on src/main/java/com/samoilenko/onlinebookstore/dto/BookRequestDto.java
> +    @NotBlank
It has message by default for example`
  "timestamp": "2024-05-02T17:08:30.7277764",
    "status": "BAD_REQUEST",
    "errors": [
        "title не должно быть пустым"
    ]`

2024-05-07 15:04 UTC, andrii-hoienko approved these changes
Good job!

2024-05-08 06:59 UTC, merged